### PR TITLE
Solo branch commit seed script

### PR DESCRIPTION
**Pull request by kevinwgutierrez**

### CODE REVIEW

**Comment by bbalbon** [comment]
@kevinwgutierrez looks good

**Comment by bbalbon** [comment]
@kevinwgutierrez I think you're okay to merge? Seems maybe it was already reviewed?

**Comment by kevinwgutierrez** [comment]
@bbalbon weird, it doesn't show any option to create pull request for these? And I didn't manually submit a PR.

**Comment by kevinwgutierrez** [comment]
@bbalbon Oh wow, nevermind I've mixed my workflow up. Going to merge now.

**Pull request merged**
